name: flutterweatherui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.2.0
  http: ^0.13.4
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  get: ^4.6.1
  firebase_database: ^9.0.6
  firebase_core: ^1.12.0
  flutter_switch: ^0.3.2
  #intl: ^0.15.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
  - assets/