name: flutterweatherui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.2.0  #used for text styling throughout the app.
  http: ^0.13.4         #package that allows for api calls in the app.
  shared_preferences:   #used to store data and get it when the app reloads.
  provider: ^6.0.2      #Packages allows for inherited widgets in the app.
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
  - assets/